name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Hostinger
        run: |
          ssh -o StrictHostKeyChecking=no -p 65002 u435110291@154.56.33.165 "
          cd /home/u435110291/domains/jmaturana.link/public_html/pizzapp  && git pull origin main"
