name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup initial project
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          if [ ! -d ${{ secrets.PROJECT_PATH }} ]; then
            echo 'La carpeta no existe. Creándola y clonando el repositorio...';
            mkdir -p ${{ secrets.PROJECT_PATH }};
            git clone git@github.com:${{ github.repository }}.git ${{ secrets.PROJECT_PATH }};
          fi"

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          cd ${{ secrets.PROJECT_PATH }} && git pull origin main"
